# Generated by Django 5.0 on 2024-01-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orderdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='creted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='stripe_payment_intent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
